module.exports = {
  theme: {
    darkSelector: '.dark-mode',
    colors: {
      light: {
        default: '#fdfafa',
        primary: '#5555CA',
        secondary: '#042586',
        accent: '#BFCFFF',
        danger: '#809FFF',
        text: '#252e42',
        transparent: 'transparent',
      },
      dark: {
        default: '#252e42',
        primary: '#09e1fd',
        secondary: '#06a6b1',
        accent: '#c2fbff',
        danger: '#84f7ff',
        text: '#ebf1f4',
        transparent: 'transparent',
      },
    },
    inset: {
      0: '0',
      '-0.5': '-0.125rem',
      '-1': '-0.025rem',
      '-1.5': '-0.375rem',
      '-2': '-0.5rem',
      '-2.5': '-0.625rem',
      '-3': '-0.75rem',
      '-4': '-1.0rem',
    },
    extend: {
      spacing: {
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.6666667%',
        '5/6': '83.3333333%',
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12': '83.333333%',
        '11/12': '91.666667%',
      },
    },
  },
  variants: {
    backgroundColor: [
      'dark',
      'dark-hover',
      'dark-focus',
      'dark-group-hover',
      'dark-even',
      'dark-odd',
      'hover',
      'responsive',
      'group-hover',
      'even',
      'odd',
      'focus',
    ],
    backgroundImage: ['hover', 'focus', 'dark'],
    borderColor: [
      'dark',
      'dark-hover',
      'dark-focus',
      'dark-active',
      'dark-focus-within',
      'hover',
      'responsive',
      'group-hover',
      'focus',
    ],
    borderWidth: ['hover', 'focus', 'dark'],
    textColor: [
      'focus',
      'dark',
      'dark-hover',
      'dark-focus',
      'dark-active',
      'hover',
      'responsive',
      'group-hover',
    ],
    gradientColorStops: ['active', 'group-hover', 'dark'],
    divideColor: [
      'dark',
      'dark-hover',
      'dark-active',
      'hover',
      'responsive',
      'group-hover',
    ],
    ringColor: ['responsive', 'dark', 'focus-within', 'focus'],
    ringWidth: ['responsive', 'dark', 'focus-within', 'focus'],
    outline: [
      'dark',
      'dark-hover',
      'dark-focus',
      'dark-active',
      'group-hover',
      'hover',
      'focus',
      'active',
      'responsive',
    ],
    inset: [
      'focus',
      'dark',
      'dark-hover',
      'dark-focus',
      'dark-active',
      'hover',
      'responsive',
      'group-hover',
    ],
  },
  plugins: [require('tailwindcss-dark-mode')()],
  purge: ['./src/**/*.html', './src/**/*.vue', './src/**/*.jsx'],
}
